// Catálogo preparado para receber séries de fontes oficiais. Nesta versão, valor é sempre null.
export const modules = [
  { id: "economia", label: "Economia", icon: "◷", description: "Acompanhe preços, atividade econômica, juros, câmbio e contas públicas.", scope: "Inflação · PIB · juros · câmbio · contas públicas", indicators: ["ipca", "pib", "selic", "cambio", "contas-publicas"] },
  { id: "politica", label: "Política", icon: "§", description: "Entenda propostas, votações, comissões e etapas do processo legislativo.", scope: "Projetos · votações · comissões · atividade legislativa", indicators: [] },
  { id: "emprego", label: "Emprego", icon: "↗", description: "Consulte desocupação, renda e vínculos formais com recortes compatíveis.", scope: "Desocupação · renda · formalização", indicators: ["desocupacao", "renda", "formalizacao"] },
  { id: "saude", label: "Saúde", icon: "+", description: "Indicadores de acesso, vacinação e estrutura dos serviços de saúde.", scope: "Acesso · vacinação · estrutura", indicators: ["acesso-saude", "vacinacao", "estrutura-saude"] },
  { id: "educacao", label: "Educação", icon: "▤", description: "Acompanhe aprendizagem, matrículas e fluxo escolar.", scope: "Aprendizagem · matrículas · fluxo escolar", indicators: ["aprendizagem", "matriculas", "fluxo-escolar"] },
  { id: "seguranca", label: "Segurança", icon: "⌑", description: "Consulte indicadores de violência e seus recortes por estado.", scope: "Violência · ocorrências · recortes estaduais", indicators: ["violencia", "homicidios", "ocorrencias"] },
  { id: "impostos", label: "Impostos", icon: "%", description: "Explore arrecadação, tributos e medidas de carga tributária.", scope: "Arrecadação · tributos · carga tributária", indicators: ["arrecadacao", "tributos", "carga-tributaria"] },
  { id: "estados", label: "Estados", icon: "⌖", description: "Compare unidades da Federação respeitando período e definição de cada série.", scope: "Comparação territorial · séries · unidades da Federação", indicators: ["desocupacao", "violencia", "arrecadacao"] },
];

export const indicators = [
  { id: "ipca", name: "Inflação", shortName: "IPCA", value: null, unit: "%", module: "economia", definition: "Variação do Índice Nacional de Preços ao Consumidor Amplo, medida pelo IBGE para acompanhar a mudança de preços de uma cesta de produtos e serviços." , period: "Sem período integrado", source: "IBGE · fonte prevista", publishedAt: null, frequency: "Mensal", methodology: "O índice depende da população-objetivo, da cesta, da área de abrangência e do mês de referência. A série e seus metadados oficiais serão vinculados quando a integração estiver disponível.", status: "Integração pendente" },
  { id: "selic", name: "Taxa básica de juros", shortName: "Selic", value: null, unit: "% a.a.", module: "economia", definition: "Taxa básica de juros da economia brasileira, definida pelo Comitê de Política Monetária do Banco Central.", period: "Sem período integrado", source: "Banco Central do Brasil · fonte prevista", publishedAt: null, frequency: "A cada reunião do Copom", methodology: "A taxa em vigor deve ser identificada pela data de início e vinculada à decisão oficial correspondente. Nenhuma taxa atual é exibida nesta versão.", status: "Integração pendente" },
  { id: "desocupacao", name: "Taxa de desocupação", shortName: "Desocupação", value: null, unit: "% da força de trabalho", module: "emprego", definition: "Proporção de pessoas desocupadas em relação à força de trabalho, segundo os critérios da pesquisa de referência.", period: "Sem período integrado", source: "IBGE · PNAD Contínua · fonte prevista", publishedAt: null, frequency: "Trimestral (referência a confirmar por série)", methodology: "A comparação exige manter a mesma população, abrangência geográfica, conceito de ocupação e período da PNAD Contínua.", status: "Integração pendente" },
  { id: "arrecadacao", name: "Arrecadação federal", shortName: "Arrecadação", value: null, unit: "R$", module: "impostos", definition: "Receitas administradas pela Receita Federal do Brasil, conforme o recorte da publicação oficial selecionada.", period: "Sem período integrado", source: "Receita Federal do Brasil · fonte prevista", publishedAt: null, frequency: "Mensal (publicação a confirmar por série)", methodology: "O conceito pode variar entre arrecadação administrada, receitas totais e valores nominais ou corrigidos. O painel apresentará o recorte e a unidade da série integrada.", status: "Integração pendente" },
  { id: "pib", name: "Produto Interno Bruto", shortName: "PIB", value: null, unit: "R$ ou variação percentual", module: "economia", definition: "Medida do valor dos bens e serviços finais produzidos no país durante um período, conforme as Contas Nacionais.", period: "Sem período integrado", source: "IBGE · Contas Nacionais · fonte prevista", publishedAt: null, frequency: "Trimestral e anual", methodology: "Resultados nominais, variação real e comparações com períodos anteriores são medidas distintas e serão identificadas separadamente.", status: "Integração pendente" },
  { id: "cambio", name: "Câmbio", shortName: "Câmbio", value: null, unit: "R$ por moeda", module: "economia", definition: "Cotação de referência de moeda estrangeira, com tipo de taxa, horário e convenção explicitados.", period: "Sem período integrado", source: "Banco Central do Brasil · fonte prevista", publishedAt: null, frequency: "Diária (série a definir)", methodology: "A cotação depende do tipo de referência e do horário de apuração. Não é exibida cotação atual nesta versão.", status: "Integração pendente" },
  { id: "contas-publicas", name: "Contas públicas", shortName: "Contas públicas", value: null, unit: "R$", module: "economia", definition: "Receitas, despesas, resultado e dívida do setor público conforme o conceito oficial selecionado.", period: "Sem período integrado", source: "Tesouro Nacional · fonte prevista", publishedAt: null, frequency: "Mensal (série a definir)", methodology: "Os conceitos de resultado primário, nominal e dívida não são intercambiáveis. A ficha indicará setor, período e critério contábil.", status: "Integração pendente" },
  { id: "renda", name: "Rendimento do trabalho", shortName: "Renda", value: null, unit: "R$", module: "emprego", definition: "Rendimento do trabalho observado na pesquisa selecionada, com identificação do conceito e da população abrangida.", period: "Sem período integrado", source: "IBGE · PNAD Contínua · fonte prevista", publishedAt: null, frequency: "Trimestral (referência a confirmar por série)", methodology: "Rendimento habitual e efetivo, valores nominais e reais e média e mediana devem aparecer separados.", status: "Integração pendente" },
  { id: "formalizacao", name: "Vínculos formais", shortName: "Formalização", value: null, unit: "Vínculos", module: "emprego", definition: "Indicador de emprego com vínculo formal segundo a base administrativa identificada.", period: "Sem período integrado", source: "Ministério do Trabalho e Emprego · fonte prevista", publishedAt: null, frequency: "Mensal (série a definir)", methodology: "Admissões, desligamentos, estoque de vínculos e pessoas empregadas representam medidas diferentes.", status: "Integração pendente" },
  { id: "acesso-saude", name: "Acesso à saúde", shortName: "Acesso", value: null, unit: "A definir por indicador", module: "saude", definition: "Medida de acesso a serviços de saúde cujo conceito, população e abrangência dependerão da série selecionada.", period: "Sem período integrado", source: "Ministério da Saúde · fonte prevista", publishedAt: null, frequency: "A definir por série", methodology: "A ficha indicará se a medida se refere à oferta, utilização, cobertura ou tempo de espera. Esses conceitos não serão combinados.", status: "Integração pendente" },
  { id: "vacinacao", name: "Cobertura vacinal", shortName: "Vacinação", value: null, unit: "%", module: "saude", definition: "Proporção da população-alvo vacinada para imunobiológico e esquema especificados.", period: "Sem período integrado", source: "Ministério da Saúde · fonte prevista", publishedAt: null, frequency: "A definir por imunobiológico", methodology: "Cobertura pode superar 100% por diferenças entre doses, estimativas populacionais e registros. A série informará vacina, dose e população-alvo.", status: "Integração pendente" },
  { id: "estrutura-saude", name: "Estrutura de saúde", shortName: "Estrutura", value: null, unit: "Unidades / equipes", module: "saude", definition: "Recursos físicos ou equipes cadastradas nos sistemas públicos, conforme a base e a data de referência.", period: "Sem período integrado", source: "Ministério da Saúde · fonte prevista", publishedAt: null, frequency: "A definir por base", methodology: "Cadastro, habilitação e funcionamento são estados diferentes. O painel identificará qual conceito cada série representa.", status: "Integração pendente" },
  { id: "aprendizagem", name: "Aprendizagem", shortName: "Aprendizagem", value: null, unit: "Escala do indicador", module: "educacao", definition: "Medida de aprendizagem de avaliação identificada, com etapa de ensino e população-alvo explicitadas.", period: "Sem período integrado", source: "INEP · fonte prevista", publishedAt: null, frequency: "Conforme calendário da avaliação", methodology: "Resultados de avaliações diferentes ou etapas distintas não são diretamente comparáveis sem harmonização metodológica.", status: "Integração pendente" },
  { id: "matriculas", name: "Matrículas", shortName: "Matrículas", value: null, unit: "Matrículas", module: "educacao", definition: "Registros de matrícula na etapa, rede e período letivo definidos pela fonte estatística.", period: "Sem período integrado", source: "INEP · Censo Escolar · fonte prevista", publishedAt: null, frequency: "Anual", methodology: "Matrículas não equivalem necessariamente ao número de estudantes únicos. Etapa, modalidade e rede serão discriminadas.", status: "Integração pendente" },
  { id: "fluxo-escolar", name: "Fluxo escolar", shortName: "Fluxo escolar", value: null, unit: "%", module: "educacao", definition: "Medidas de aprovação, reprovação ou abandono, identificadas por etapa e coorte escolar.", period: "Sem período integrado", source: "INEP · fonte prevista", publishedAt: null, frequency: "Anual", methodology: "Taxas de fluxo dependem de coorte, etapa, rede e regra de cálculo. A ficha indicará a definição utilizada.", status: "Integração pendente" },
  { id: "violencia", name: "Violência", shortName: "Violência", value: null, unit: "A definir por indicador", module: "seguranca", definition: "Indicador de violência a ser delimitado por tipo de ocorrência, fonte administrativa ou estatística e território.", period: "Sem período integrado", source: "Ministério da Justiça e Segurança Pública · fonte prevista", publishedAt: null, frequency: "A definir por indicador", methodology: "Registros administrativos refletem notificações e critérios de coleta. Incidência registrada não representa necessariamente a totalidade dos fatos.", status: "Integração pendente" },
  { id: "homicidios", name: "Mortes violentas intencionais", shortName: "Mortes violentas", value: null, unit: "Número / taxa", module: "seguranca", definition: "Classificação de mortes violentas conforme a fonte estatística ou administrativa selecionada.", period: "Sem período integrado", source: "Ministério da Justiça e Segurança Pública · fonte prevista", publishedAt: null, frequency: "A definir por fonte", methodology: "Classificações e denominadores podem diferir entre bases. Número absoluto e taxa serão apresentados como medidas distintas.", status: "Integração pendente" },
  { id: "ocorrencias", name: "Ocorrências registradas", shortName: "Ocorrências", value: null, unit: "Registros", module: "seguranca", definition: "Registros administrativos contabilizados segundo a tipologia, cobertura e regras de consolidação da base.", period: "Sem período integrado", source: "Ministério da Justiça e Segurança Pública · fonte prevista", publishedAt: null, frequency: "A definir por base", methodology: "Diferenças de registro, tipificação e cobertura entre estados limitam comparações diretas.", status: "Integração pendente" },
  { id: "tributos", name: "Tributos", shortName: "Tributos", value: null, unit: "R$", module: "impostos", definition: "Receita de tributo identificado, em esfera e período definidos pela fonte oficial.", period: "Sem período integrado", source: "Receita Federal do Brasil · fonte prevista", publishedAt: null, frequency: "A definir por publicação", methodology: "A ficha indicará tributo, esfera de governo e valores nominais ou corrigidos. Rubricas tributárias não serão somadas sem compatibilidade.", status: "Integração pendente" },
  { id: "carga-tributaria", name: "Carga tributária", shortName: "Carga tributária", value: null, unit: "% do PIB", module: "impostos", definition: "Relação entre a arrecadação de tributos e o Produto Interno Bruto segundo metodologia explicitada.", period: "Sem período integrado", source: "Tesouro Nacional · fonte prevista", publishedAt: null, frequency: "Anual", methodology: "A composição dos tributos e a versão do PIB adotadas serão informadas para permitir comparação entre séries.", status: "Integração pendente" },
];

export const updates = [
  { label: "Catálogo de módulos", detail: "Oito temas organizados para consulta pública.", type: "Produto" },
  { label: "Fichas metodológicas", detail: "Campos preparados para definição, período, fonte e notas.", type: "Transparência" },
  { label: "Integrações oficiais", detail: "Nenhuma série foi sincronizada nesta versão.", type: "Dados" },
];

export const proposals = [
  { id: "demo-senado", house: "Senado", subject: "Exemplo fictício de proposta sobre mobilidade urbana", stage: "Etapa demonstrativa · comissão", movedAt: null, code: "PL 0000/20XX", party: "Conteúdo criado apenas para demonstrar a interface", timeline: ["Apresentação · exemplo", "Comissão · exemplo", "Parecer · pendente", "Plenário · pendente"] },
  { id: "demo-camara", house: "Câmara", subject: "Exemplo fictício de projeto sobre acesso à informação", stage: "Etapa demonstrativa · aguardando votação", movedAt: null, code: "PL 0000/20XX", party: "Conteúdo criado apenas para demonstrar a interface", timeline: ["Apresentação · exemplo", "Comissão · exemplo", "Votação · pendente", "Sanção · pendente"] },
];

// Unidades da Federação e nomes usados nas fichas e nos rótulos do mapa.
export const states = [
  { uf: "RR", name: "Roraima" }, { uf: "AP", name: "Amapá" },
  { uf: "AM", name: "Amazonas" }, { uf: "PA", name: "Pará" }, { uf: "MA", name: "Maranhão" },
  { uf: "AC", name: "Acre" }, { uf: "RO", name: "Rondônia" }, { uf: "MT", name: "Mato Grosso" }, { uf: "TO", name: "Tocantins" }, { uf: "PI", name: "Piauí" }, { uf: "CE", name: "Ceará" }, { uf: "RN", name: "Rio Grande do Norte" },
  { uf: "PB", name: "Paraíba" }, { uf: "PE", name: "Pernambuco" }, { uf: "BA", name: "Bahia" }, { uf: "AL", name: "Alagoas" }, { uf: "SE", name: "Sergipe" },
  { uf: "DF", name: "Distrito Federal" }, { uf: "GO", name: "Goiás" }, { uf: "MS", name: "Mato Grosso do Sul" }, { uf: "MG", name: "Minas Gerais" }, { uf: "ES", name: "Espírito Santo" },
  { uf: "SP", name: "São Paulo" }, { uf: "RJ", name: "Rio de Janeiro" }, { uf: "PR", name: "Paraná" }, { uf: "SC", name: "Santa Catarina" }, { uf: "RS", name: "Rio Grande do Sul" },
];
